# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "create new file"
    touch /tmp/test1sh.txt
    echo "hello this is me" >> /tmp/test1sh.txt
    ls -lart /tmp/test1sh.txt
  displayName: 'File Create'

- script: |
    echo "put some values"
    echo -e "hello\nhai" >> /tmp/test1sh.txt
    cat /tmp/test1sh.txt
  displayName: 'Display file contents'
